### PR TITLE
fix title html element

### PR DESCRIPTION
**Pull request by 4cdn**
Hopefully starts displaying a generating a value to put between the title html elements on /overchan.boardname-0.html pages

Almost everything else in srnvd2 and nntpchan repos I think reference Board including line 56 of this which seems to be what we are trying to generate a page of off.

I'm way over my head here. Untested too.

### CODE REVIEW

**Comment by 4cdn** [comment]
I feel like this probably fucks up something else somewhere in the code that relies on it.

maybe it just works

**Comment by majestrate** [comment]
newsgroup and board are terms that are used interchangeably all throughout the codebase but they effectively are one in the same, at least for now. the NNTPMessage interface type https://github.com/majestrate/srndv2/blob/master/src/srnd/message.go#L44 does not have a function called Board so this code won't compile. good try tho, keep at it, this code could be a lot better @~@

**Comment by majestrate** [comment]
what you could do is add a new Function to the BoardModel interface called Title and then figure out how to make that configurable :^) https://github.com/majestrate/srndv2/blob/master/src/srnd/model.go#L101

**Comment by 4cdn** [comment]
Sounds terrifying.

```
lines 382 - 384

func (self post) Name() string {
  return self.name
}

lines 370 - 372

func (self post) Board() string {
  return self.board
}

line 168

param["name"] = fmt.Sprintf("page %d for %s", self.page, self.board)
```

As I understand it this indicates self.board is not self.name

yet

```
func (self boardModel) Name() string {
  return self.board
}
```

unless its more magic interchangability (also idk how to code), then the value for Board is never being gotten as the boardModel function?

also

```
line 473

param["frontend"] = self.Board()
```

seems you intended the navbar to say "Thread xxxxxxxxxxxxxxxxxx on overchan.frontendname" rather than "Thread xxxxxxxxxxxxxxxxxx on overchan.boardname"

**Comment by majestrate** [comment]
no activity, closing for now.

**Pull request closed without merging**
